// scripts/fetch-icons.mjs
// Run: node scripts/fetch-icons.mjs
// Pulls the curated game-icons.net subset and writes src/ui/icons/data.ts + CREDITS.md
import { writeFileSync, mkdirSync } from 'node:fs'

// name -> [author, slug]  (game-icons.net CC-BY 3.0)
const ICONS = {
  // roles
  tank: ['willdabeast', 'round-shield'],
  brawler: ['skoll', 'fist'],
  mage: ['lorc', 'crystal-ball'],
  assassin: ['lorc', 'plain-dagger'],
  support: ['lorc', 'winged-emblem'],
  swarm: ['lorc', 'backup'],
  ranged: ['lorc', 'high-shot'],
  building: ['delapouite', 'tower-flag'],
  spell: ['lorc', 'scroll-unfurled'],
  // spell sub-types
  'spell-damage': ['lorc', 'fireball'],
  'spell-heal': ['sbed', 'health-normal'],
  'spell-buff': ['lorc', 'wingfoot'],
  'spell-slow': ['lorc', 'snowflake-2'],
  // ui / nav
  battle: ['lorc', 'crossed-swords'],
  practice: ['lorc', 'target-arrows'],
  deck: ['faithtoken', 'card-pick'],
  loot: ['skoll', 'open-treasure-chest'],
  ladder: ['lorc', 'trophy'],
  wallet: ['delapouite', 'wallet'],
  guest: ['delapouite', 'person'],
  lock: ['lorc', 'padlock'],
  check: ['delapouite', 'check-mark'],
  crown: ['lorc', 'crown'],
  elixir: ['sbed', 'water-drop'],
  plus: ['badges', 'plus'],
  back: ['delapouite', 'previous-button'],
}

const RAW = (author, slug) =>
  `https://raw.githubusercontent.com/game-icons/icons/master/${author}/${slug}.svg`

const paths = {}
const credits = []
for (const [name, [author, slug]] of Object.entries(ICONS)) {
  const url = RAW(author, slug)
  const res = await fetch(url)
  if (!res.ok) { console.error(`MISS ${name}: ${url} -> ${res.status}`); continue }
  const svg = await res.text()
  // Skip the black background square "M0 0h512v512H0z" — grab the icon path (white fill)
  const allPaths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/gi)]
  const iconPath = allPaths.find(m => !m[1].startsWith('M0 0h512v512H0z')) || allPaths[0]
  if (!iconPath) { console.error(`NO PATH ${name}: ${url}`); continue }
  paths[name] = iconPath[1]
  credits.push(`- **${name}** — "${slug}" by ${author} — https://game-icons.net/1x1/${author}/${slug}.html`)
  console.log(`OK ${name}`)
}

mkdirSync('src/ui/icons', { recursive: true })
const ts =
  `// AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit by hand.\n` +
  `// game-icons.net, CC-BY 3.0. See CREDITS.md.\n` +
  `export const ICON_PATHS: Record<string, string> = ${JSON.stringify(paths, null, 2)}\n`
writeFileSync('src/ui/icons/data.ts', ts)
writeFileSync(
  'src/ui/icons/CREDITS.md',
  `# Icon credits\n\nAll icons from game-icons.net, licensed CC-BY 3.0 (https://creativecommons.org/licenses/by/3.0/).\n\n${credits.join('\n')}\n`,
)
console.log(`\nWrote ${Object.keys(paths).length}/${Object.keys(ICONS).length} icons.`)
